trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'Your-Azure-Subscription-Service-Connection'
  appLocation: 'app'  # Path to your application code
  apiLocation: 'api'  # Path to your API code (if any)
  outputLocation: 'build'  # Build output directory
  staticWebAppName: 'your-static-web-app-name'
  environment: 'Production'

stages:
- stage: BuildAndDeploy
  displayName: 'Build and Deploy ChatGPT App'
  jobs:
  - job: BuildAndDeployJob
    displayName: 'Build and Deploy Job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureStaticWebApp@0
      inputs:
        app_location: $(appLocation)
        api_location: $(apiLocation)
        output_location: $(outputLocation)
        azure_static_web_apps_api_token: $(DEPLOY_TOKEN)
        sku: 'Standard'
        is_merging_branches: false
        production_branch: 'main'
        environment: $(environment)
      env:
        azure_static_web_apps_api_token: $(DEPLOY_TOKEN)
